os:
  - linux
  - osx
# Enable Trusty dist, Standard is ancient.
dist: trusty
# Enable C++ support
language: cpp
# # Compiler selection
compiler:
  - clang
  - gcc
# Build steps
script:
  - mkdir build && cd build
  - cmake ..
#  - if [[ $TRAVIS_OS_NAME = osx ]]; then cmake -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl/lib -DOPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include ..; else cmake ..; fi
  - make
  - make jwttool
  - make tests && make test
before_install:
  - if [[ $TRAVIS_OS_NAME = linux ]]; then sudo apt-get -qq update; else brew update; fi
  - if [[ $TRAVIS_OS_NAME = linux ]]; then sudo apt-get install -y libjansson-dev; else brew install jansson; fi
  - if [[ $TRAVIS_OS_NAME = linux ]]; then sudo apt-get install -y libboost-all-dev; fi
  - if [[ $TRAVIS_OS_NAME = osx ]]; then brew install openssl; fi
