# Enable Trusty dist, Standard is ancient.
dist: trusty
# Enable C++ support
language: cpp
# # Compiler selection
compiler:
  - clang
  - gcc
# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make
  - make tests && make test
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libjansson-dev
  - sudo apt-get install -y libboost-dev
